### ISSUE TITLE
 No module named 'opencage'

### ISSUE THREAD

**Issue by BabuBhaiya9** [akashblackhat/no-infoga.py#1]
Traceback (most recent call last):
  File "/root/Desktop/Tools/no-infoga.py/no-infoga.py", line 5, in <module>
    from opencage.geocoder import OpenCageGeocode
ModuleNotFoundError: No module named 'opencage'

**Comment by akashblackhat** [comment]
Tq

**Comment by akashblackhat** [comment]
Please fix the error

**Comment by PriyanshuPatel09** [comment]
Traceback (most recent call last):
File "/root/Desktop/Tools/no-infoga.py/no-infoga.py", line 5, in
from opencage.geocoder import OpenCageGeocode
ModuleNotFoundError: No module named 'opencage'


This same error occured with me also

**Comment by akashblackhat** [comment]
Fixed!
